routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::view('/', 'dashboard');
	Route::view('/home', 'dashboard')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('wilayah', 'WilayahController');
	Route::resource('murid', 'MuridController');

});

resources/views/controlSidebar.blade.php
<!-- Create the tabs -->
<ul class="nav nav-tabs nav-justified control-sidebar-tabs">
  <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
  <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
</ul>
<!-- Tab panes -->
<div class="tab-content">
  <!-- Home tab content -->
  <div class="tab-pane active" id="control-sidebar-home-tab">
    <h3 class="control-sidebar-heading">Recent Activity</h3>
    <ul class="control-sidebar-menu">
      <li>
        <a href="javascript:;">
          <i class="menu-icon fa fa-birthday-cake bg-red"></i>

          <div class="menu-info">
            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

            <p>Will be 23 on April 24th</p>
          </div>
        </a>
      </li>
    </ul>
    <!-- /.control-sidebar-menu -->

    <h3 class="control-sidebar-heading">Tasks Progress</h3>
    <ul class="control-sidebar-menu">
      <li>
        <a href="javascript:;">
          <h4 class="control-sidebar-subheading">
            Custom Template Design
            <span class="pull-right-container">
                <span class="label label-danger pull-right">70%</span>
              </span>
          </h4>

          <div class="progress progress-xxs">
            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
          </div>
        </a>
      </li>
    </ul>
    <!-- /.control-sidebar-menu -->

  </div>
  <!-- /.tab-pane -->
  <!-- Stats tab content -->
  <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
  <!-- /.tab-pane -->
  <!-- Settings tab content -->
  <div class="tab-pane" id="control-sidebar-settings-tab">
    <form method="post">
      <h3 class="control-sidebar-heading">General Settings</h3>

      <div class="form-group">
        <label class="control-sidebar-subheading">
          Report panel usage
          <input type="checkbox" class="pull-right" checked>
        </label>

        <p>
          Some information about this general settings option
        </p>
      </div>
      <!-- /.form-group -->
    </form>
  </div>
  <!-- /.tab-pane -->
</div>

resources/views/dashboard.blade.php
@extends('template')

@section('title')
  Dashboard
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Dashboard</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-dashboard"></i>
            <h3 class="box-title">Dashboard</h3>
		</div>
		<div class="box-body">
			<p>
				Selamat, {{ Auth::user()->name }}. Anda berhasil Login sebagai:
			</p>
			@role('administrator')
				<h3>Administrator</h3>
			@endrole
			@role('supervisor')
				<h3>Supervisor</h3>
			@endrole
			@role('operator')
				<h3>Operator</h3>
			@endrole
		</div>
		<div class="box-footer">

		</div>
	</div>
@endsection

@section('script')
  <script type="text/javascript">


  </script>
@endsection

resources/views/footer.blade.php
<!-- To the right -->
<div class="pull-right hidden-xs">
  {{ config('app.developer') }}
</div>
<!-- Default to the left -->
<strong>Copyright &copy; {{ date('Y') }} <a href="#">Company</a>.</strong> All rights reserved.

resources/views/header.blade.php
<!-- Logo -->
    <a href="{{ url('/') }}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>Admin</b>LTE</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <div style="color: white; font-size: 15pt; float: left; margin-top: 10px; margin-left: 20px; letter-spacing: 1;">
          {{ config('app.name') }}
      </div>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">

          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              @if (!empty(Auth::user()->foto))
                <img src="{{ asset('images/users/'.Auth::user()->foto) }}" class="user-image" alt="User Image">
              @else
                <img src="{{ asset('images/users/default.jpg') }}" class="user-image" alt="User Image">
              @endif

              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ Auth::user()->name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                @if (!empty(Auth::user()->foto))
                  <img src="{{ asset('images/users/'.Auth::user()->foto) }}" class="img-circle" alt="User Image">
                @else
                  <img src="{{ asset('images/users/default.jpg') }}" class="img-circle" alt="User Image">
                @endif


                <p>
                  {{ Auth::user()->name }}
                  <small>Aktif sejak {{ Auth::user()->created_at->diffForHumans() }}</small>
                </p>
              </li>

              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{{-- {{ route('user.show', Auth::user()->uuid) }} --}}" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{ route('logout') }}" class="btn btn-default btn-flat"
                          onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                  <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                  </form>
                </div>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/master.blade.php
@extends('template')

@section('title')
  Master
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Master</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-dashboard"></i>
            <h3 class="box-title">Master</h3>
		</div>
		<div class="box-body">

		</div>
		<div class="box-footer">

		</div>
	</div>
@endsection

@section('script')
  <script type="text/javascript">


  </script>
@endsection

resources/views/sidebar.blade.php
<!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar user panel (optional) -->
      <div class="user-panel">
        <div class="pull-left image">
          @if (!empty(Auth::user()->foto))
            <img src="{{ asset('images/users/'.Auth::user()->foto) }}" class="img-circle" alt="User Image">
          @else
            <img src="{{ asset('images/users/default.jpg') }}" class="img-circle" alt="User Image">
          @endif
        </div>
        <div class="pull-left info">
          <p>{{  Auth::user()->name }}</p>
          <!-- Status -->
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">PENGATURAN USER</li>
        <li class="{{ set_active(['user.index', 'user.show']) }}"><a href="{{ route('user.index') }}"><i class="fa fa-users"></i> <span>User</span></a></li>
        <li class="{{ set_active(['role.index']) }}"><a href="{{ route('role.index') }}"><i class="fa fa-signal"></i> <span>Role</span></a></li>
        <li class="header">PENGATURAN MASTER</li>
        <li class="{{ set_active(['periode.index','periode.edit','periode.create']) }}"><a href="{{ url('periode') }}"><i class="fa fa-calendar"></i> <span>Periode</span></a></li>
        <li class="{{ set_active(['kategori.index','kategori.edit','kategori.create']) }}"><a href="{{ url('kategori') }}"><i class="fa fa-list"></i> <span>kategori</span></a></li>
        <li class="{{ set_active(['wilayah.index','wilayah.edit','wilayah.create']) }}"><a href="{{ url('wilayah') }}"><i class="fa fa-map"></i> <span>Wilayah</span></a></li>
        <li class="{{ set_active(['murid.index','murid.edit','murid.create']) }}"><a href="{{ url('murid') }}"><i class="fa fa-user"></i> <span>Murid</span></a></li>


      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->

resources/views/template.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{{ config('app.name') }}</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ asset('bower_components/Ionicons/css/ionicons.min.css') }}">
  <link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.css') }}">
  <link rel="stylesheet" href="{{ asset('dist/css/skins/_all-skins.css') }}">
  <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/css/checkboxStyle.css') }}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{{ asset('bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

  <!-- DATATABLES -->
  <link rel="stylesheet" href="{{ asset('DataTables/css/dataTables.bootstrap.min.css') }}">
  <!-- SWEET ALERT2 -->
  <link rel="stylesheet" href="{{ asset('public/sweetalert2/dist/sweetalert2.min.css') }}">
  <!-- Select2 -->
  <link rel="stylesheet" href="{{ asset('plugins/select2/css/select2.css') }}">
  <link rel="stylesheet" href="{{ asset('plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css') }}">

{{-- 
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]--> --}}

  {{-- <!-- Google Font -->
  @if (@fsockopen("www.google.com", 80))
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
  @endif --}}

  <style>
    .form-group{
      margin-bottom: 5px;
    }

    .form-radio{
         -webkit-appearance: none;
         -moz-appearance: none;
         appearance: none;
         display: inline-block;
         position: relative;
         background-color: #f1f1f1;
         color: #666;
         top: 2px;
         height: 16px;
         width: 16px;
         cursor: pointer;
         border: 1px solid #d0d8e5;
    }
    .form-radio:checked::before{
         position: absolute;
         left: 4px;
         content: '\02143';
         transform: rotate(35deg);
    }
    .form-radio:hover{
         background-color: #f7f7f7;
    }
    .form-radio:checked{
         background-color: #f1f1f1;
    }

  </style>

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">
    @include('header')
  </header>

  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    @include('sidebar')
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        @yield('title')
      </h1>
      <ol class="breadcrumb">
        @yield('breadcrumb')
      </ol>
    </section>

    <!-- Main content -->
    <section class="content container-fluid">

      @yield('content')

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    @include('footer')
  </footer>

</div>
<!-- ./wrapper -->

<!-- jQuery 3 -->
<script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('bower_components/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<!-- daterangepicker -->
<script src="{{ asset('bower_components/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('bower_components/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
<!-- datepicker -->
<script src="{{ asset('bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js') }}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ asset('bower_components/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('dist/js/adminlte.min.js') }}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('path') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('dist/js/demo.js') }}"></script>
<!-- DATATABLES -->
<script src="{{ asset('DataTables/js/jquery.dataTables.min.js') }}" charset="utf-8"></script>
<script src="{{ asset('DataTables/js/dataTables.bootstrap.min.js') }}" charset="utf-8"></script>
<script src="{{ asset('sweetalert2/dist/sweetalert2.all.min.js') }}" charset="utf-8"></script>
<!-- Select2 -->
<script src="{{ asset('plugins/select2/js/select2.full.min.js') }}"></script>

<script type="text/javascript">
  $(function () {
      //Initialize Select2 Elements
      $('.select2').select2()

      //Initialize Select2 Elements
      $('.select2bs4').select2({
      theme: 'bootstrap4'
      })

      $('#datatable').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": true,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
      });
      $("#example1").DataTable({
          "responsive": true,
          "autoWidth": false,
      });
      $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false,
          "responsive": true,
      });
  });

  function ribuan(x) {
      return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".")
  }
</script>
@yield('script')

</body>
</html>