routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::view('/', 'dashboard');
	Route::view('/home', 'dashboard')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('wilayah', 'WilayahController');
	Route::resource('murid', 'MuridController');

});

resources/views/master/kategori-edit.blade.php
@extends('template')

@section('title')
  Kategori 
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Kategori</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Kategori
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('kategori.update', $kategori->id) }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ json_encode($sukses)  }}</strong>
                    </div>
                @endif
                @csrf @method('PUT')
                <input type="text" name="id" value="{{ $kategori->id }}" hidden>
                <div class="form-group groupName">
                    <label for="nama" class="col-sm-1 control-label">Nama</label>
                    <div class="col-sm-4">
                        <input type="text" name="nama" class="form-control" value="{{ $kategori->nama }}">
                        <small class="text-danger errorNama"></small>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/kategori-tambah.blade.php
@extends('template')

@section('title')
  Kategori
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Kategori</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Kategori
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('kategori.store') }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ json_encode($sukses->nama)  }}</strong>
                    </div>
                @endif
                @csrf @method('POST')
                <div class="form-group groupName">
                    <label for="nama" class="col-sm-1 control-label">Nama</label>
                    <div class="col-sm-4">
                        <input type="text" name="nama" class="form-control" value="">
                        <small class="text-danger errorNama"></small>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/kategori.blade.php
@extends('template')

@section('title')
  Kategori <a class="btn btn-default btn-sm btn-flat" href="{{ route('kategori.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Kategori</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Kategori

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>Nama</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
						@isset($kategori)
							@foreach ($kategori as $item)
								<tr>
									<th>{{ $item->nama }}</th>
									<th>
										<a type="button" href="{{ route('kategori.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
									</th>
								</tr>
							@endforeach
						@endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/murid-edit.blade.php
@extends('template')

@section('title')
  Murid 
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Murid</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Murid
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('murid.update', $murid->id) }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                @csrf @method('PUT')
                <input type="text" name="id" value="{{ $murid->id }}" hidden>
                <div class="col-md-6">
                  <div class="form-group groupName">
                      <label for="nama" class="col-sm-3 control-label">Nama</label>
                      <div class="col-sm-9">
                          <input type="text" name="nama" class="form-control" value="{{ $murid->nama }}">
                      </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label for="alamat" class="col-sm-3 control-label">Alamat</label>
                    <div class="col-sm-9">
                        <textarea name="alamat" class="form-control">{{ $murid->alamat }}</textarea>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                      <label for="tempat" class="col-sm-3 control-label">Tempat</label>
                      <div class="col-sm-9">
                          <input type="text" name="tempat" class="form-control" value="{{ $murid->tempat }}">
                      </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label for="tanggal_lahir" class="col-sm-3 control-label">Tanggal Lahir</label>
                    <div class="col-sm-9">
                        <input type="date" name="tanggal_lahir" class="form-control" value="{{ $murid->tanggal_lahir }}">
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label class="col-sm-3 control-label">Wilayah</label>
                    <div class="col-sm-9">
                      <select name="id_wilayah" class="form-control select2" value="{{ $murid->id_wilayah }}">
                        <option value="">Pilih</option>
                        @foreach ($wilayah as $item)
                          @if ($item->id == $murid->id_wilayah)
                            <option value="{{ $item->id }}" selected>{{ $item->nama_wilayah }}</option>
                          @else
                            <option value="{{ $item->id }}">{{ $item->nama_wilayah }}</option>
                          @endif
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label class="col-sm-3 control-label">Kategori</label>
                    <div class="col-sm-9">
                      <select name="id_kategori" class="form-control select2" value="{{ $murid->id_kategori }}">
                        <option value="">Pilih</option>
                        @foreach ($kategori as $item)
                          @if ($item->id == $murid->id_kategori)
                            <option value="{{ $item->id }}" selected>{{ $item->nama }}</option>
                          @else
                            <option value="{{ $item->id }}">{{ $item->nama }}</option>
                          @endif
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/master/murid-tambah.blade.php
@extends('template')

@section('title')
  Murid
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Murid</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Murid
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('murid.store') }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{-- <strong>{{ json_encode($sukses->nama)  }}</strong> --}}
                    </div>
                @endif
                @csrf @method('POST')
                <div class="col-md-6">
                  <div class="form-group groupName">
                      <label for="nama" class="col-sm-3 control-label">Nama</label>
                      <div class="col-sm-9">
                          <input type="text" name="nama" class="form-control" value="">
                      </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label for="alamat" class="col-sm-3 control-label">Alamat</label>
                    <div class="col-sm-9">
                        <textarea name="alamat" class="form-control" value=""></textarea>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                      <label for="tempat" class="col-sm-3 control-label">Tempat</label>
                      <div class="col-sm-9">
                          <input type="text" name="tempat" class="form-control" value="">
                      </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label for="tanggal_lahir" class="col-sm-3 control-label">Tanggal Lahir</label>
                    <div class="col-sm-9">
                        <input type="date" name="tanggal_lahir" class="form-control" value="">
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label class="col-sm-3 control-label">Wilayah</label>
                    <div class="col-sm-9">
                      <select name="id_wilayah" class="form-control select2">
                        <option value="">Pilih</option>
                        @foreach ($wilayah as $item)
                          <option value="{{ $item->id }}">{{ $item->nama_wilayah }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label class="col-sm-3 control-label">Kategori</label>
                    <div class="col-sm-9">
                      <select name="id_kategori" class="form-control select2">
                        <option value="">Pilih</option>
                        @foreach ($kategori as $item)
                          <option value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                      </select>
                    </div>
                  </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/master/murid.blade.php
@extends('template')

@section('title')
  Murid <a class="btn btn-default btn-sm btn-flat" href="{{ route('murid.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Murid</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Murid

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{-- <strong>{{ $errors->has('nama') ? 'has-error' : '' }}</strong> --}}
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered" id="datatable">
					<thead>
						<tr>
							<th>Nama</th>
                            <th>Tempat, Tanggal Lahir</th>
                            <th>Alamat</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
                        @isset($murid)
                            @foreach ($murid as $item)
                                <tr>
                                    <th>{{ $item->nama }}</th>
                                    <th>{{ $item->tempat }}, {{ $item->tanggal_lahir }}</th>
                                    <th>{{ $item->alamat }}</th>
                                    <th>
                                        <a type="button" href="{{ route('murid.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
                                    </th>
                                </tr>
                            @endforeach
                        @endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/master/periode-edit.blade.php
@extends('template')

@section('title')
  Periode 
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Periode</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Periode
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('periode.update', $periode->id) }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ json_encode($sukses)  }}</strong>
                    </div>
                @endif
                @csrf @method('PUT')
                <input type="text" name="id" value="{{ $periode->id }}" hidden>
                <div class="form-group groupName">
                    <label for="nama" class="col-sm-1 control-label">Nama</label>
                    <div class="col-sm-4">
                        <input type="text" name="nama" class="form-control" value="{{ $periode->nama }}">
                        <small class="text-danger errorNama"></small>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/periode-tambah.blade.php
@extends('template')

@section('title')
  Periode
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Periode</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Periode
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('periode.store') }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ json_encode($sukses->nama)  }}</strong>
                    </div>
                @endif
                @csrf @method('POST')
                <div class="form-group groupName">
                    <label for="nama" class="col-sm-1 control-label">Nama</label>
                    <div class="col-sm-4">
                        <input type="text" name="nama" class="form-control" value="">
                        <small class="text-danger errorNama"></small>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/periode.blade.php
@extends('template')

@section('title')
  Periode <a class="btn btn-default btn-sm btn-flat" href="{{ route('periode.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Periode</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Periode

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>Nama</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
						@isset($periode)
							@foreach ($periode as $item)
								<tr>
									<th>{{ $item->nama }}</th>
									<th>
										<a type="button" href="{{ route('periode.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
									</th>
								</tr>
							@endforeach
						@endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/wilayah-edit.blade.php
@extends('template')

@section('title')
  Wilayah 
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Wilayah</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Wilayah
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('wilayah.update', $wilayah->id) }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{-- <strong>{{ $sukses }}</strong> --}}
                    </div>
                @endif
                @csrf @method('PUT')
                <input type="text" name="id" value="{{ $wilayah->id }}" hidden>
                <div class="col-md-6">
                  <div class="form-group groupName">
                      <label for="nama_wilayah" class="col-sm-3 control-label">Nama Walayah</label>
                      <div class="col-sm-9">
                          <input type="text" name="nama_wilayah" class="form-control" value="{{ $wilayah->nama_wilayah }}">
                          <small class="text-danger errorNamaWilayah"></small>
                      </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label for="jarak" class="col-sm-3 control-label">Jarak</label>
                    <div class="col-sm-9">
                        <input type="number" name="jarak" class="form-control" value="{{ $wilayah->jarak }}">
                        <small class="text-danger errorJarak"></small>
                    </div>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group groupName">
                    <label for="harga" class="col-sm-3 control-label">Harga</label>
                    <div class="col-sm-9">
                        <input type="number" name="harga" class="form-control" value="{{ $wilayah->harga }}">
                        <small class="text-danger errorHarga"></small>
                    </div>
                  </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/master/wilayah.blade.php
@extends('template')

@section('title')
  Wilayah <a class="btn btn-default btn-sm btn-flat" href="{{ route('wilayah.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Wilayah</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Wilayah

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        {{-- <strong>{{ $errors->has('nama') ? 'has-error' : '' }}</strong> --}}
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>Nama Wilayah</th>
                            <th>Jarak</th>
                            <th>Harga</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
                        @isset($wilayah)
                            @foreach ($wilayah as $item)
                                <tr>
                                    <th>{{ $item->nama_wilayah }}</th>
                                    <th>{{ $item->jarak }}</th>
                                    <th>{{ $item->harga }}</th>
                                    <th>
                                        <a type="button" href="{{ route('wilayah.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
                                    </th>
                                </tr>
                            @endforeach
                        @endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection