routes/web.php
<?php

Auth::routes();

Route::group(['middleware' => 'auth'], function () {
	Route::view('/', 'dashboard');
	Route::view('/home', 'dashboard')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('wilayah', 'WilayahController');
	Route::resource('murid', 'MuridController');

});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use LaratrustUserTrait;
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use DataTables;
use Illuminate\Http\Request;
use Validator;

class UserController extends Controller {

	public function index() {
		return view('user.user');
	}

	public static function datalist() {
		$user = \App\User::all();
		return Datatables::of($user)
			->addIndexColumn()
			->addColumn('role', function ($user) {
				foreach ($user->roles as $d) {
					$r[] = ' ' . $d->display_name;
				}
				return implode(',', $r);
			})
			->addColumn('edit', function ($user) {
				return '<button type="button" onclick="editForm(' . $user->id . ')" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></button>';
			})
			->rawColumns(['edit'])
			->make(true);
	}

	public static function getRole() {
		$role = \App\Role::all();
		return $role;
	}

	public function create() {
		//
	}

	public function store(Request $request) {
		$cek = Validator::make($request->all(), [
			'name' => 'required|string|max:255',
			'email' => 'required|string|email|max:255|unique:users',
			'password' => 'required|string|min:6|confirmed',
			'role' => 'required',
		]);

		if ($cek->passes()) {
			$user = \App\User::create([
				'name' => $request['name'],
				'email' => $request['email'],
				'foto' => NULL,
				'password' => bcrypt($request['password']),
			]);
			foreach ($request['role'] as $d) {
				$role = \App\Role::where('name', $d)->first();
				$user->attachRole($role);
			}
			return response()->json(['success' => '1', 'message' => 'User berhasil ditambahkan.']);
		} else {
			return response()->json(['errors' => $cek->errors()]);
		}
	}

	public function show($id) {
		//
	}

	public function edit($id) {
		$data['user'] = \App\User::findOrFail($id);
		$data['role'] = $data['user']->roles;
		return $data;
	}

	public function update(Request $request, $id) {
		$user = \App\User::findOrFail($id);
		$cek = Validator::make($request->all(), [
			'name' => 'required|string|max:255',
			'email' => 'required|string|email|max:255|unique:users,email,' . $id,
			'password' => 'nullable|string|min:6|confirmed',
			'role' => 'required',
		]);

		if ($cek->passes()) {
			$password = !empty($request['password']) ? bcrypt($request['password']) : $user->password;
			$user->update([
				'name' => $request['name'],
				'email' => $request['email'],
				'foto' => NULL,
				'password' => $password,
			]);
			foreach ($user->roles as $d) {
				$user->detachRole($d);
			}
			foreach ($request['role'] as $d) {
				$role = \App\Role::where('name', $d)->first();
				$user->attachRole($role);
			}

			return response()->json(['success' => '1', 'message' => 'User berhasil di update']);
		} else {
			return response()->json(['errors' => $cek->errors()]);
		}

	}

	public function destroy($id) {
		//
	}
}

resources/views/user/role.blade.php
@extends('template')

@section('title')
  Role / Hak Akses
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Role / Hak Akses</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-signal"></i>
            <h3 class="box-title">Role / Hak Akses</h3>
		</div>
		<div class="box-body">
			<div class="table-responsive">
				<table class="table table-hover table-bordered table-condensed">
					<thead>
						<tr>
							<th>No</th>
							<th>Nama Role</th>
							<th>Keterangan</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>
{{-- Role Modal --}}
<div class="modal fade" id="modalRole">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body">
				<form id="formRole" method="POST" class="form-horizontal">
					@csrf @method('PUT')
					<input type="hidden" name="id" value="">
					<div class="form-group">
						<label for="display_name" class="col-sm-3 control-label">Nama Role</label>
						<div class="col-sm-9">
							<input type="text" name="display_name" class="form-control">
						</div>
					</div>
					<div class="form-group">
						<label for="description" class="col-sm-3 control-label">Keterangan</label>
						<div class="col-sm-9">
							<textarea name="description" class="form-control"></textarea>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary btn-flat" onclick="saveForm()">Save</button>
			</div>
		</div>
	</div>
</div>
@endsection

@section('script')
  <script type="text/javascript">
	//SHOW DATA
    var table;
    table = $('.table').DataTable({
      'language': {
          'url': '/DataTables/datatable-language.json',
      },
      autoWidth: false,
      processing: true,
      serverSide: true,
      ajax: '{{ route('role-data') }}',
      columns: [
          {data: 'DT_RowIndex', searchable: false},
          {data: 'display_name'},
          {data: 'description'},
          {data: 'edit', searchable: false}
      ]
    });

    function editForm(id) {
    	$('#modalRole').modal('show');
    	$('.modal-title').text('Edit Role')
    	$.ajax({
    		url: '/role/'+id+'/edit',
    		type: 'GET',
    		dataType: 'json',
    	})
    	.done(function(data) {
    		$('input[name="id"]').val(data.id)
    		$('input[name="display_name"]').val(data.display_name)
    		$('textarea[name="description').val(data.description)
    	});

    }

    function saveForm() {
    	var data = $('#formRole').serialize();
    	var id = $('input[name="id"]').val();

    	$.ajax({
    		url: '/role/'+id,
    		type: 'POST',
    		dataType: 'json',
    		data: data,
    	})
    	.done(function(data) {
    		if (data.success == true) {
				$('#formRole')[0].reset()
				$('#modalRole').modal('hide')
				table.ajax.reload()
				Swal({
				  position: 'middle',
				  type: 'success',
				  title: data.message,
				  showConfirmButton: false,
				  timer: 1500
				})
			}
    	});

    }

  </script>
@endsection

resources/views/user/user.blade.php
@extends('template')

@section('title')
  User <button class="btn btn-default btn-sm btn-flat" onclick="addForm()"><i class="fa fa-plus"></i> TAMBAH</button>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">User</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-users"></i>
            <h3 class="box-title">
            Data User

        	</h3>
		</div>
		<div class="box-body">
			<div class="table-responsive">
				<table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>No</th>
							<th>Nama</th>
							<th>Email</th>
							<th>Role</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>
{{-- MODAL USER --}}
<div class="modal fade" id="modalUser">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title"></h4>
			</div>
			<div class="modal-body">
				<form method="POST" class="form-horizontal" id="formUser">
					@csrf @method('POST')
					<input type="hidden" name="id" value="">

					<div class="form-group groupName">
						<label for="name" class="col-sm-4 control-label">Nama Lengkap</label>
						<div class="col-sm-8">
							<input type="text" name="name" class="form-control" value="">
							<small class="text-danger errorName"></small>
						</div>
					</div>
					<div class="form-group groupEmail">
						<label for="email" class="col-sm-4 control-label">Alamat Email</label>
						<div class="col-sm-8">
							<input type="text" name="email" class="form-control" value="">
							<small class="text-danger errorEmail"></small>
						</div>
					</div>
					<div class="form-group groupPassword">
						<label for="password" class="col-sm-4 control-label">Password</label>
						<div class="col-sm-8">
							<input type="password" name="password" class="form-control" value="">
							<small class="text-danger errorPassword"></small>
						</div>
					</div>
					<div class="form-group">
						<label for="password" class="col-sm-4 control-label">Konfirmasi Password</label>
						<div class="col-sm-8">
							<input type="password" name="password_confirmation" class="form-control" value="">
						</div>
					</div>
					<div class="form-group groupRole">
						<label for="password" class="col-sm-4 control-label">Role User</label>
						<div class="col-sm-8">
							<div id="viewRole"></div>
							<small class="text-danger errorRole"></small>
						</div>
					</div>

				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary btn-flat" onclick="saveForm()">Save</button>
			</div>
		</div>
	</div>
</div>

@endsection

@section('script')
  <script type="text/javascript">
	//SHOW DATA
    var table;
    table = $('.table').DataTable({
      'language': {
          'url': '/DataTables/datatable-language.json',
      },
      autoWidth: false,
      processing: true,
      serverSide: true,
      ajax: '{{ route('user-data') }}',
      columns: [
          {data: 'DT_RowIndex', searchable: false},
          {data: 'name'},
          {data: 'email'},
          {data: 'role'},
          {data: 'edit', searchable: false}
      ]
    });

    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

    //EDIT FORM
    function editForm(id) {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Edit User')
    	$.ajax({
    		url: '/user/'+id+'/edit',
    		type: 'GET',
    		dataType: 'json',
    	})
    	.done(function(data) {
    		$('input[name="id"]').val(id)
    		$('input[name="_method"]').val('PATCH')
    		$('input[name="name"]').val(data.user.name)
    		$('input[name="email"]').val(data.user.email)
    		$('input[type="checkbox"]').attr('checked', false);
    		$.each(data.role, function(i, role) {
    			 $('input[value="'+role.name+'"]').attr('checked', true)
    		});
    	});

    }

    //GET ROLE
    jQuery(document).ready(function() {
    	$.ajax({
    		url: '{{ route('getRole') }}',
    		type: 'GET',
    		dataType: 'json',
    	})
    	.done(function(data) {
    		$('#viewRole').empty();
    		$.each(data, function(index, val) {
    			$('#viewRole').append('<div class="col-sm-6"><input type="checkbox" name="role[]" class="form-radio" value="'+val.name+'"> '+val.display_name+'</div>')
    		});
    	});

    });

    //SAVE FORM
	function saveForm() {
		resetForm()

		var data = $('#formUser').serialize();
		var id = $('input[name="id"]').val();

		if (id != '') {
			url = '/user/'+id
		} else {
			url = '{{ route('user.store') }}'
		}

		$.ajax({
			url: url,
			type: 'POST',
			dataType: 'json',
			data: data,
		})
		.done(function(data) {
			if (data.errors) {
				if (data.errors.name) {
					$('.groupName').addClass('has-error')
					$('.errorName').text(data.errors.name[0])
				}
				if (data.errors.email) {
					$('.groupEmail').addClass('has-error')
					$('.errorEmail').text(data.errors.email[0])
				}
				if (data.errors.password) {
					$('.groupPassword').addClass('has-error')
					$('.errorPassword').text(data.errors.password[0])
				}
				if (data.errors.role) {
					$('.groupRole').addClass('has-error')
					$('.errorRole').text(data.errors.role[0])
				}
			}

			if (data.success == 1) {
				$('#formUser')[0].reset()
				$('#modalUser').modal('hide')
				table.ajax.reload()
				Swal({
				  position: 'middle',
				  type: 'success',
				  title: data.message,
				  showConfirmButton: false,
				  timer: 1500
				})
			}
		});

	}

  </script>
@endsection